commit_message: "[ci skip]"

files:
  - source: fastlane/metadata/android/en-US/*description
    translation: /fastlane/metadata/android/%locale%/%original_file_name%
  - source: app/src/main/res/values/strings.xml
    translation: /app/src/main/res/values-%android_code%/strings.xml
  - source: app/src/main/res/values/arrays.xml
    translation: /app/src/main/res/values-%android_code%/arrays.xml
    translatable_elements:
      - '/resources/string-array[@name=''exif_library_entries'']'
      - '/resources/string-array[@name=''exif_library_pixymeta_entries'']'
      - '/resources/string-array[@name=''exiv2SkipLevel_entries'']'
